//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodrowLuo.Common.Modes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> BeeWeight { get; set; }
        public string Color { get; set; }
        public Nullable<int> Number { get; set; }
        public string SendUser { get; set; }
        public string SendPhone { get; set; }
        public string SendAddress { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string ReceviedUser { get; set; }
        public string Receviedhone { get; set; }
        public string ReceviedAddress { get; set; }
        public Nullable<System.DateTime> ReceviedTime { get; set; }
        public Nullable<System.DateTime> SaleTime { get; set; }
        public Nullable<int> BeeStatus { get; set; }
    }
}
